import {
  AlignmentType,
  BorderStyle,
  Document,
  ExternalHyperlink,
  HeadingLevel,
  ImageRun,
  LevelFormat,
  Packer,
  Paragraph,
  ParagraphChild,
  ShadingType,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType
} from 'docx'
import { dataUrlToBytes } from '../pdf/text-raster'

interface InlineStyle {
  bold?: boolean
  italics?: boolean
  underline?: boolean
  strike?: boolean
  color?: string
  highlightHex?: string
  size?: number
  font?: string
  link?: string
}

export interface DocxWriteOptions {
  title?: string
  author?: string
  rightToLeft: boolean
  defaultFont?: string
  defaultSize?: number
}

const HEADINGS: Record<string, (typeof HeadingLevel)[keyof typeof HeadingLevel]> = {
  H1: HeadingLevel.HEADING_1,
  H2: HeadingLevel.HEADING_2,
  H3: HeadingLevel.HEADING_3,
  H4: HeadingLevel.HEADING_4,
  H5: HeadingLevel.HEADING_5,
  H6: HeadingLevel.HEADING_6
}

/**
 * Converts the editor's HTML into a real .docx.
 *
 * The traversal is intentionally shallow-but-broad: it understands the subset
 * of HTML the editor can produce (headings, lists, tables, images, links and
 * inline character formatting) and ignores anything else rather than failing.
 */
export async function htmlToDocx(html: string, options: DocxWriteOptions): Promise<Uint8Array> {
  const container = document.createElement('div')
  container.innerHTML = html

  const children: (Paragraph | Table)[] = []
  for (const node of Array.from(container.childNodes)) {
    children.push(...convertBlock(node, {}, options))
  }
  if (children.length === 0) children.push(new Paragraph({ text: '' }))

  const file = new Document({
    title: options.title,
    creator: options.author || 'Alcode Editor',
    description: 'Generated by Alcode Editor',
    styles: {
      default: {
        document: {
          run: {
            font: options.defaultFont ?? (options.rightToLeft ? 'Arial' : 'Calibri'),
            size: (options.defaultSize ?? 11) * 2
          },
          paragraph: { spacing: { after: 160, line: 300 } }
        }
      }
    },
    numbering: {
      config: [
        {
          reference: 'alcode-numbering',
          levels: [0, 1, 2, 3].map((level) => ({
            level,
            format: LevelFormat.DECIMAL,
            text: `%${level + 1}.`,
            alignment: AlignmentType.START,
            style: { paragraph: { indent: { left: 480 * (level + 1), hanging: 260 } } }
          }))
        }
      ]
    },
    sections: [
      {
        properties: {
          page: { margin: { top: 1134, bottom: 1134, left: 1134, right: 1134 } }
        },
        children
      }
    ]
  })

  const blob = await Packer.toBlob(file)
  return new Uint8Array(await blob.arrayBuffer())
}

interface BlockContext {
  list?: 'bullet' | 'number'
  level?: number
  quote?: boolean
}

function convertBlock(
  node: Node,
  context: BlockContext,
  options: DocxWriteOptions
): (Paragraph | Table)[] {
  if (node.nodeType === Node.TEXT_NODE) {
    const text = node.textContent?.trim()
    if (!text) return []
    return [paragraphOf([new TextRun({ text })], node.parentElement, context, options)]
  }
  if (node.nodeType !== Node.ELEMENT_NODE) return []

  const element = node as HTMLElement
  const tag = element.tagName

  if (tag === 'BR') return []
  if (tag === 'HR') {
    return [
      new Paragraph({
        text: '',
        border: { bottom: { style: BorderStyle.SINGLE, size: 6, color: 'C8CCD4', space: 1 } }
      })
    ]
  }

  if (tag === 'TABLE') return [convertTable(element, options)]

  if (tag === 'UL' || tag === 'OL') {
    const kind = tag === 'UL' ? 'bullet' : 'number'
    const level = (context.level ?? -1) + 1
    const output: (Paragraph | Table)[] = []
    for (const item of Array.from(element.children)) {
      if (item.tagName !== 'LI') continue
      const nested = Array.from(item.children).filter(
        (child) => child.tagName === 'UL' || child.tagName === 'OL'
      )
      const clone = item.cloneNode(true) as HTMLElement
      for (const child of Array.from(clone.children)) {
        if (child.tagName === 'UL' || child.tagName === 'OL') child.remove()
      }
      output.push(
        paragraphOf(inlineChildren(clone, {}, options), clone, { list: kind, level }, options)
      )
      for (const sublist of nested) {
        output.push(...convertBlock(sublist, { level }, options))
      }
    }
    return output
  }

  if (tag === 'BLOCKQUOTE') {
    const output: (Paragraph | Table)[] = []
    for (const child of Array.from(element.childNodes)) {
      output.push(...convertBlock(child, { ...context, quote: true }, options))
    }
    return output.length > 0
      ? output
      : [paragraphOf(inlineChildren(element, {}, options), element, { ...context, quote: true }, options)]
  }

  if (tag === 'DIV' || tag === 'SECTION' || tag === 'ARTICLE' || tag === 'MAIN') {
    const blockChildren = Array.from(element.childNodes).filter(isBlockNode)
    if (blockChildren.length > 0) {
      return Array.from(element.childNodes).flatMap((child) => convertBlock(child, context, options))
    }
  }

  if (tag === 'IMG') {
    const image = imageRunOf(element as HTMLImageElement)
    return image ? [new Paragraph({ children: [image] })] : []
  }

  return [paragraphOf(inlineChildren(element, {}, options), element, context, options)]
}

function isBlockNode(node: Node): boolean {
  if (node.nodeType !== Node.ELEMENT_NODE) return false
  return /^(P|DIV|H[1-6]|UL|OL|TABLE|BLOCKQUOTE|HR|SECTION|ARTICLE)$/.test(
    (node as HTMLElement).tagName
  )
}

function paragraphOf(
  children: ParagraphChild[],
  element: HTMLElement | null,
  context: BlockContext,
  options: DocxWriteOptions
): Paragraph {
  const tag = element?.tagName ?? 'P'
  const alignment = alignmentOf(element, options)

  return new Paragraph({
    children: children.length > 0 ? children : [new TextRun({ text: '' })],
    heading: HEADINGS[tag],
    bidirectional: options.rightToLeft,
    alignment,
    bullet: context.list === 'bullet' ? { level: context.level ?? 0 } : undefined,
    numbering:
      context.list === 'number'
        ? { reference: 'alcode-numbering', level: context.level ?? 0 }
        : undefined,
    indent: context.quote ? { start: 480 } : undefined,
    border: context.quote
      ? { left: { style: BorderStyle.SINGLE, size: 12, color: 'D6D9E0', space: 12 } }
      : undefined
  })
}

function alignmentOf(
  element: HTMLElement | null,
  options: DocxWriteOptions
): (typeof AlignmentType)[keyof typeof AlignmentType] | undefined {
  const align = element?.style?.textAlign
  if (!align) return undefined
  if (align === 'center') return AlignmentType.CENTER
  if (align === 'justify') return AlignmentType.JUSTIFIED
  if (align === 'right') return options.rightToLeft ? AlignmentType.START : AlignmentType.END
  if (align === 'left') return options.rightToLeft ? AlignmentType.END : AlignmentType.START
  return undefined
}

function inlineChildren(
  element: HTMLElement,
  inherited: InlineStyle,
  options: DocxWriteOptions
): ParagraphChild[] {
  const output: ParagraphChild[] = []

  for (const node of Array.from(element.childNodes)) {
    if (node.nodeType === Node.TEXT_NODE) {
      const text = node.textContent ?? ''
      if (!text) continue
      output.push(runOf(text, inherited, options))
      continue
    }
    if (node.nodeType !== Node.ELEMENT_NODE) continue

    const child = node as HTMLElement
    const tag = child.tagName

    if (tag === 'BR') {
      output.push(new TextRun({ text: '', break: 1 }))
      continue
    }
    if (tag === 'IMG') {
      const image = imageRunOf(child as HTMLImageElement)
      if (image) output.push(image)
      continue
    }

    const style = mergeStyle(inherited, child)
    if (tag === 'A') {
      const href = child.getAttribute('href') ?? ''
      const inner = inlineChildren(child, { ...style, color: style.color ?? '0A84FF' }, options)
      if (href && /^(https?|mailto):/i.test(href)) {
        output.push(new ExternalHyperlink({ link: href, children: inner }))
      } else {
        output.push(...inner)
      }
      continue
    }
    output.push(...inlineChildren(child, style, options))
  }
  return output
}

function mergeStyle(inherited: InlineStyle, element: HTMLElement): InlineStyle {
  const tag = element.tagName
  const style: InlineStyle = { ...inherited }
  if (tag === 'B' || tag === 'STRONG') style.bold = true
  if (tag === 'I' || tag === 'EM') style.italics = true
  if (tag === 'U') style.underline = true
  if (tag === 'S' || tag === 'STRIKE' || tag === 'DEL') style.strike = true
  if (tag === 'CODE' || tag === 'PRE') style.font = 'Consolas'

  const inline = element.style
  if (inline.fontWeight && Number(inline.fontWeight) >= 600) style.bold = true
  if (inline.fontStyle === 'italic') style.italics = true
  if (inline.textDecorationLine?.includes('underline') || inline.textDecoration?.includes('underline')) {
    style.underline = true
  }
  if (inline.textDecorationLine?.includes('line-through') || inline.textDecoration?.includes('line-through')) {
    style.strike = true
  }
  if (inline.color) style.color = cssColorToHex(inline.color) ?? style.color
  if (inline.backgroundColor) style.highlightHex = cssColorToHex(inline.backgroundColor) ?? style.highlightHex
  if (inline.fontFamily) style.font = inline.fontFamily.split(',')[0].replace(/["']/g, '').trim()
  if (inline.fontSize) {
    const size = Number.parseFloat(inline.fontSize)
    if (Number.isFinite(size) && inline.fontSize.endsWith('px')) style.size = Math.round(size * 0.75)
  }
  return style
}

function runOf(text: string, style: InlineStyle, options: DocxWriteOptions): TextRun {
  return new TextRun({
    text,
    bold: style.bold,
    italics: style.italics,
    underline: style.underline ? {} : undefined,
    strike: style.strike,
    color: style.color,
    font: style.font,
    size: style.size ? style.size * 2 : undefined,
    rightToLeft: options.rightToLeft,
    shading: style.highlightHex
      ? { type: ShadingType.CLEAR, fill: style.highlightHex, color: 'auto' }
      : undefined
  })
}

function imageRunOf(element: HTMLImageElement): ImageRun | null {
  const source = element.getAttribute('src') ?? ''
  if (!source.startsWith('data:')) return null
  const mime = /^data:([^;]+)/.exec(source)?.[1] ?? 'image/png'
  const type = mime.includes('jpeg') || mime.includes('jpg')
    ? 'jpg'
    : mime.includes('gif')
      ? 'gif'
      : mime.includes('bmp')
        ? 'bmp'
        : 'png'

  const width = element.naturalWidth || Number(element.getAttribute('width')) || 480
  const height = element.naturalHeight || Number(element.getAttribute('height')) || 320
  const maxWidth = 560
  const scale = width > maxWidth ? maxWidth / width : 1

  return new ImageRun({
    type,
    data: dataUrlToBytes(source),
    transformation: { width: Math.round(width * scale), height: Math.round(height * scale) }
  })
}

function convertTable(element: HTMLElement, options: DocxWriteOptions): Table {
  const rows: TableRow[] = []
  const htmlRows = element.querySelectorAll('tr')

  htmlRows.forEach((htmlRow) => {
    const cells: TableCell[] = []
    htmlRow.querySelectorAll('td, th').forEach((htmlCell) => {
      const cell = htmlCell as HTMLElement
      const isHeader = cell.tagName === 'TH'
      cells.push(
        new TableCell({
          children: [
            new Paragraph({
              children: inlineChildren(cell, { bold: isHeader || undefined }, options),
              bidirectional: options.rightToLeft
            })
          ],
          shading: isHeader ? { type: ShadingType.CLEAR, fill: 'F2F3F7', color: 'auto' } : undefined,
          margins: { top: 80, bottom: 80, left: 120, right: 120 }
        })
      )
    })
    if (cells.length > 0) rows.push(new TableRow({ children: cells }))
  })

  if (rows.length === 0) rows.push(new TableRow({ children: [new TableCell({ children: [new Paragraph('')] })] }))

  return new Table({
    rows,
    width: { size: 100, type: WidthType.PERCENTAGE },
    visuallyRightToLeft: options.rightToLeft,
    borders: {
      top: { style: BorderStyle.SINGLE, size: 4, color: 'C8CCD4' },
      bottom: { style: BorderStyle.SINGLE, size: 4, color: 'C8CCD4' },
      left: { style: BorderStyle.SINGLE, size: 4, color: 'C8CCD4' },
      right: { style: BorderStyle.SINGLE, size: 4, color: 'C8CCD4' },
      insideHorizontal: { style: BorderStyle.SINGLE, size: 4, color: 'C8CCD4' },
      insideVertical: { style: BorderStyle.SINGLE, size: 4, color: 'C8CCD4' }
    }
  })
}

function cssColorToHex(value: string): string | null {
  const rgbMatch = /rgba?\(\s*(\d+)[,\s]+(\d+)[,\s]+(\d+)/i.exec(value)
  if (rgbMatch) {
    return [rgbMatch[1], rgbMatch[2], rgbMatch[3]]
      .map((part) => Number(part).toString(16).padStart(2, '0'))
      .join('')
      .toUpperCase()
  }
  const hexMatch = /^#([0-9a-f]{3}|[0-9a-f]{6})$/i.exec(value.trim())
  if (!hexMatch) return null
  const hex = hexMatch[1]
  return (hex.length === 3 ? hex.split('').map((c) => c + c).join('') : hex).toUpperCase()
}
